-- MySQL Script generated by MySQL Workbench
-- Wed Jan 22 18:05:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador do usuário que contém auto incremento afim de contabilizar a quantidade de usuários no sistema.',
  `Name` TEXT(45) NOT NULL COMMENT 'Campo para que o usuário possa colocar seu nome completo.',
  `e-mail` VARCHAR(45) NOT NULL COMMENT 'Campo para o usuário registrar o seu e-mail, o mesmo que será utilizado para login no sistema do site.',
  `password` TEXT(16) NOT NULL COMMENT 'Campo para registro da senha do usuário, que ele utilizará para realizar login. O mesmo campo está limitao a 16 caracteres.',
  `access` ENUM('root', 'padrao') NOT NULL COMMENT 'Este campo definirá o acesso que o usuário terá ao sistema, sendo Root a permissão para administrar as funções do site em si e o padrão a permissão para visualizar e editar mensagens, visualizar promoções e editar dados pessoais.',
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `e-mail_UNIQUE` (`e-mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Promoções`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Promoções` (
  `idPromoções` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de promoções que contém auto incremento afim de contabilizar a quantidade de promoções no sistema.',
  `Data_Validade` DATE NOT NULL COMMENT 'Campo dedicado ao registro de uma data limite para que aquela promoção fique no sistema. Após a data definida, a promoção passará para o status \'Suspensa\'.',
  `Título` TEXT(45) NOT NULL COMMENT 'Campo destinado para inserir o título da promoção.',
  `Descrição` LONGTEXT NOT NULL COMMENT 'Campo dedicado a descrição do produto que será comercializado no sistema.',
  `Status` ENUM('ativa', 'suspensa') NOT NULL COMMENT 'Este campo está relacionado a data de validade, sendo que será definido o status de \'ativa\' para aqueles produtos que posseum a data dentro do limite de validade e \'suspensa\' para aqueles que ultrapassarem a data de validade.',
  `Valor` FLOAT NOT NULL COMMENT 'Campo destinado ao valor do produto.',
  `Condições` MEDIUMTEXT NOT NULL COMMENT 'Campo destinado a condições da promoção, como ela irá funcionar e outras características da mesma.',
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`idPromoções`, `Users_idUsers`),
  INDEX `fk_Promoções_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  CONSTRAINT `Editar_Promoções`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inscrições`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inscrições` (
  `idInscrições` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de inscrições que contém auto incremento afim de contabilizar a quantidade de inscrições no sistema.',
  `e-mail` VARCHAR(255) NOT NULL COMMENT 'Campo para o inscrito registrar o seu e-mail, o mesmo que será necessário para envio de mensagem e registro de cadastro no site.',
  `data_cadastro` DATE NOT NULL COMMENT 'Campo armazenador da data correspondente ao cadastro do e-mail no sistema.',
  PRIMARY KEY (`idInscrições`, `e-mail`),
  INDEX `e-mail_idx` (`e-mail` ASC) VISIBLE,
  UNIQUE INDEX `e-mail_UNIQUE` (`e-mail` ASC) VISIBLE,
  CONSTRAINT `e-mail`
    FOREIGN KEY (`e-mail`)
    REFERENCES `mydb`.`Users` (`e-mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensagens` (
  `idMensagens` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de mensagens que contém auto incremento afim de contabilizar a quantidade de mensagens no sistema.',
  `Name` TEXT(45) NOT NULL COMMENT 'Campo para que o usuário possa colocar seu nome completo.',
  `e-mail` VARCHAR(255) NOT NULL COMMENT 'Campo para o usuário registrar o seu e-mail, o mesmo que será utilizado para enviar a mensagem e receber a mensagem de resposta.',
  `Mensagem` LONGTEXT NOT NULL COMMENT 'Campo dedicado ao texto que acompanha o e-mail que o usuário deseja enviar ao respectivo destinatário. Nele o usuário poderá escrever a sua dúvida, comentário ou sugestão.',
  `Status` TINYINT NOT NULL COMMENT 'Campo dedicado ao status da mensagem, se True, a mensagem foi lida, se False, a mensagem ainda não foi lida pelo destinatário.',
  `Id_Users` INT NOT NULL,
  PRIMARY KEY (`idMensagens`, `Id_Users`),
  UNIQUE INDEX `e-mail_UNIQUE` (`e-mail` ASC) VISIBLE,
  INDEX `Id_Users_idx` (`Id_Users` ASC) VISIBLE,
  CONSTRAINT `Id_Users`
    FOREIGN KEY (`Id_Users`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
